FROM golang:1.22-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o ums ./cmd/server

FROM alpine:3.19
RUN apk add --no-cache ca-certificates tzdata wget
WORKDIR /app
COPY --from=builder /build/ums       ./ums
COPY --from=builder /build/configs   ./configs
COPY --from=builder /build/migrations ./migrations
EXPOSE 8081
ENTRYPOINT ["./ums"]
